# Utiliser l'image officielle PHP
FROM php8.2-cli

# Définir le dossier de travail
WORKDIR app

# Copier tout le projet dans le conteneur
COPY . app

# Lancer le serveur PHP intégré
CMD [php, -S, 0.0.0.010000, -t, .]
